istiod:
  revision: stable
  istio_cni:
    enabled: false
  pilot:
    image: pilot
    tag: 1.21.6-distroless
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
    seccompProfile:
      type: RuntimeDefault
    env:
      AUTO_RELOAD_PLUGIN_CERTS: true
      ENABLE_EXTERNAL_NAME_ALIAS: "false"
      VERIFY_CERTIFICATE_AT_CLIENT: "false"
      ENABLE_AUTO_SNI: "false"
  global:
    hub: docker.io/istio
    tag: 1.21.6-distroless
    imagePullPolicy: ""
    defaultResources:
      requests:
        cpu: 10m
        memory: 128Mi
  proxy:
    image: proxyv2
    tag: 1.21.6-distroless
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
  proxy_init:
    image: proxyv2

  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY

cni:
  revision: stable
  hub: docker.io/istio
  tag: 1.21.6-distroless
  cni:
    resourceQuotas:
      enabled: true
    cniBinDir: "/home/kubernetes/bin"
    excludeNamespaces:
      - istio-system
      - kube-system
      - istio-gateway