apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebin
  namespace: ns-nodebin
spec:
  selector:
    matchLabels:
      app: nodebin
  replicas: 1
  template:
    metadata:
      labels:
        app: nodebin
    spec:
      containers:
      - name: nodebin
        image: arnabcs10/nodebin:v2.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 443
        volumeMounts:
        - name: tls-secret
          mountPath: /etc/tls
          readOnly: true
        env:
        - name: TLS_CERT_FILE
          value: "/etc/tls/tls.crt"
        - name: TLS_KEY_FILE
          value: "/etc/tls/tls.key"
        - name: ENV
          value: "PRD"
        - name: HTTPBIN_URI
          value: "http://httpbin-svc.ns-httpbin.svc.cluster.local"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: tls-secret
        secret:
          secretName: tls-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nodebin-svc
  namespace: ns-nodebin
spec:
  selector:
    app: nodebin
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https

