apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebin
  namespace: ns-nodebin
spec:
  selector:
    matchLabels:
      app: nodebin
  replicas: 1
  template:
    metadata:
      labels:
        app: nodebin
    spec:
      containers:
      - name: nodebin
        image: arnabcs10/nodebin:v2.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: HTTPBIN_URI
          value: "https://httpbin.org/"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: nodebin-svc
  namespace: ns-nodebin
spec:
  selector:
    app: nodebin
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
