apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: ns-httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc
  namespace: ns-httpbin
spec:
  selector:
    app: httpbin
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
