apiVersion: v2
name: istio
description: Istio Helm Chart for Kubernetes
type: application
version: 0.1.0

appVersion: "1.22.6"

dependencies:
  - name: "base"
    version: "1.22.6"
    repository: "file://charts/base"
  - name: "istiod"
    version: "1.22.6"
    repository: "file://charts/istiod"
  - name: "cni"
    version: "1.22.6"
    repository: "file://charts/cni"
  # - name: "zero-trust"
  #   version: "1.22.6"
  #   repository: "file://charts/base"